<?php
// Plain text version of the report email

echo "REPORT: " . strtoupper($report['name']) . "\n";
echo str_repeat("=", 50) . "\n\n";

echo "Generated on: " . $generated_at . "\n";
echo "Report ID: #" . $report['id'] . "\n";
echo "Total Records: " . number_format($report['total_records']) . "\n";
echo "Custom View: " . ucfirst(str_replace('_', ' ', $report['custom_view'])) . "\n\n";

if (!empty($report['description'])) {
    echo "Description:\n";
    echo $report['description'] . "\n\n";
}

if ($schedule) {
    echo "SCHEDULED REPORT\n";
    echo "This is a " . ucfirst($schedule['frequency']) . " report that was automatically generated.\n\n";
}

if (isset($has_attachment) && $has_attachment) {
    echo "ATTACHMENT\n";
    echo "Complete data has been exported to: " . $attachment_name . "\n\n";
}

if (!empty($report['filters'])) {
    echo "APPLIED FILTERS:\n";
    foreach ($report['filters'] as $key => $value) {
        if (is_array($value)) {
            echo "- " . ucfirst(str_replace('_', ' ', $key)) . ": " . implode(', ', $value) . "\n";
        } else {
            echo "- " . ucfirst(str_replace('_', ' ', $key)) . ": " . $value . "\n";
        }
    }
    echo "\n";
}

if (!empty($report['data']) && count($report['data']) > 0) {
    echo "SUMMARY STATISTICS:\n";
    echo str_repeat("-", 30) . "\n";
    
    $data = $report['data'];
    $total_spend = array_sum(array_column($data, 'spend'));
    $total_impressions = array_sum(array_column($data, 'impressions'));
    $total_clicks = array_sum(array_column($data, 'clicks'));
    $avg_ctr = $total_impressions > 0 ? ($total_clicks / $total_impressions) * 100 : 0;
    $avg_roas = count($data) > 0 ? array_sum(array_column($data, 'roas')) / count($data) : 0;
    
    echo "Total Spend: $" . number_format($total_spend, 2) . "\n";
    echo "Impressions: " . number_format($total_impressions) . "\n";
    echo "Clicks: " . number_format($total_clicks) . "\n";
    echo "Average CTR: " . number_format($avg_ctr, 2) . "%\n";
    echo "Average ROAS: " . number_format($avg_roas, 2) . "\n";
    echo "Total Records: " . count($data) . "\n\n";
}

echo "This report was generated by the JJ Reporting Dashboard.\n";
echo "Dashboard: " . $dashboard_url . "\n";
echo "Support: support@yourdomain.com\n";
echo "© " . date('Y') . " JJ Reporting Dashboard. All rights reserved.\n";
?>
